import { Sensor, SensorLocation } from "./Sensor";
import { AntiTheftSystemArmedModes } from "./AntiTheftSystemArmedModes";
import { AntiTheftSystemResponse } from "./AntiTheftSystemResponse";

export interface AntiTheftSystemAPI {
    on(event: string, listener: (... args: any[]) => void): void;
    setGuestCode(ownerCode: string, guestCode: string): AntiTheftSystemResponse;
    updateOwnerCode(currentCode: string, newCode: string): AntiTheftSystemResponse;
    updateAdminCode(currentCode: string, newcode: string): AntiTheftSystemResponse;
    setProgrammingMode(adminCode: string): AntiTheftSystemResponse;
    unsetProgrammingMode(): AntiTheftSystemResponse;
    setSensor(sensor: Sensor): AntiTheftSystemResponse;
    unsetSensor(location: SensorLocation): AntiTheftSystemResponse;
    setEntryTime(seconds: number, code?: string): AntiTheftSystemResponse;
    setExitTime(seconds: number, code?: string): AntiTheftSystemResponse;
    turnOnBeep(code?: string): AntiTheftSystemResponse;
    turnOffBeep(code?: string): AntiTheftSystemResponse;
    toggleBeep(code?: string): AntiTheftSystemResponse;
    turnOnSilentAlarm(code?: string): AntiTheftSystemResponse;
    turnOffSilentAlarm(code?: string): AntiTheftSystemResponse;
    toggleSilentAlarm(code?: string): AntiTheftSystemResponse;
    getCentralPhone(): AntiTheftSystemResponse;
    setCentralPhone(phone: string): AntiTheftSystemResponse;
    unsetCentralPhone(): AntiTheftSystemResponse;
    getAdminPhone(): AntiTheftSystemResponse;
    setAdminPhone(phone: string): AntiTheftSystemResponse;
    unsetAdminPhone(): AntiTheftSystemResponse;
    getOwnerPhones(): AntiTheftSystemResponse;
    addOwnerPhone(phone: string, code?: string): AntiTheftSystemResponse;
    updateOwnerPhone(index: number, phone: string, code?: string): AntiTheftSystemResponse;
    deleteOwnerPhone(index: number, code?: string): AntiTheftSystemResponse;
    getCentralEmail(): AntiTheftSystemResponse;
    setCentralEmail(email: string): AntiTheftSystemResponse;
    unsetCentralEmail(): AntiTheftSystemResponse;
    getAdminEmail(): AntiTheftSystemResponse;
    setAdminEmail(email: string): AntiTheftSystemResponse;
    unsetAdminEmail(): AntiTheftSystemResponse;
    getOwnerEmails(): AntiTheftSystemResponse;
    addOwnerEmail(email: string, code?: string): AntiTheftSystemResponse;
    updateOwnerEmail(index: number, email: string, code?: string): AntiTheftSystemResponse;
    deleteOwnerEmail(index: number, code?: string): AntiTheftSystemResponse;
    generateSecret(): AntiTheftSystemResponse;
    validateClient(clientId: string, token: string): AntiTheftSystemResponse;
    getState(): AntiTheftSystemResponse;
    bypassOne(location: SensorLocation, code?: string): AntiTheftSystemResponse;
    bypassAll(locations: SensorLocation[], code?: string): AntiTheftSystemResponse;
    clearBypass(code?: string): AntiTheftSystemResponse;
    arm(mode: AntiTheftSystemArmedModes, code?: string): AntiTheftSystemResponse;
    disarm(code: string): AntiTheftSystemResponse;
}